name = "ModularWF"
uuid = "1521eb2b-bfa9-46ca-b1b8-6d87ef3fb17c"
authors = ["Eben60"]
version = "0.1.3"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]